# Add application configuration variables here, as shown below.

development:
  DB_NAME: ''
  DB_USER: ''
  DB_PASS: ''
  MAIL_HOST: ''
  MAIL_USER: ''
  MAIL_PASS: ''
  PAYPAL_URL: ''
  PAYPAL_PDT_AT: ''
  PAYPAL_ACCOUNT: ''

production:
  DB_NAME: ''
  DB_USER: ''
  DB_PASS: ''
  MAIL_HOST: ''
  SECRET_TOKEN: ''
  PAYPAL_URL: ''
  PAYPAL_PDT_AT: ''
  PAYPAL_ACCOUNT: ''

test:
  DB_NAME: ''
  DB_USER: ''
  DB_PASS: ''
  MAIL_HOST: ''
  FAKE_IP: ''
  PAYPAL_URL: ''
  PAYPAL_PDT_AT: ''
  PAYPAL_ACCOUNT: ''
